name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: ls -a && npm -v && npm ci
      - name: lint
        run: npm run lint
