name: learn-github-actions
on:
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - name: Setup Nodejs env
        uses: actions/setup-node@v2.1.2
      - name: Install Dependencies
        run: npm -v && npm install 
      - name: lint
        run: npm run lint
